### ISSUE TITLE
[User Security] Checklist for access checks

### ISSUE THREAD

**Issue by gayleeegayle** [OneGiantLeap/mrsfields-OIMS#21]
- [ ] Order Main Screen
- [ ] Sales Order Create
- [ ] Sales Order Update
- [ ] Disable Sales Order Update if it has a DR already
- [ ] Delivery Main Screen
- [ ] Delivery Receipt Create
- [ ] Delivery Receipt Update
- [ ] Disable DR Update if it's already approved?
- [ ] Sales Return Main Screen???
- [ ] Sales Return Create
- [ ] Sales Return Update
- [ ] Disable SR Update if it's already approved?
- [ ] Requisition Main Screen
- [ ] Requisition Voucher Create
- [ ] Requisition Voucher Update
- [ ] Disable RV Update if it's already approved?
- [ ] Purchasing Main Screen
- [ ] Purchase Order Create
- [ ] Purchase Order Update
- [ ] Disable PO Update if it's already approved?
- [ ] Receiving Main Screen
- [ ] Material Receiving Create
- [ ] Material Receiving Update
- [ ] Approval Main Screen
- [ ] DR Approval Tab
- [ ] SR Approval Tab
- [ ] RV Approval Tab
- [ ] PO Approval Tab
- [ ] Inventory Main Screen
- [ ] Current Inventory Tab
- [ ] Stock Card Tab
- [ ] Stock Card History Tab
- [ ] Adjustment Tab
- [ ] Adjustment Create
- [ ] Adjustment Update
- [ ] Item Disposition Tab
- [ ] Item Disposition Create
- [ ] Item Disposition Update
- [ ] Reports - Purchasing
- [ ] Reports - Delivery
- [ ] Reports - Material
- [ ] Reports - Other
- [ ] Reports - Production Unit Report (*Don't know its report classification yet)
- [ ] File Maintenance Main Screen
- [ ] Supplier Tab
- [ ] Supplier Create
- [ ] Supplier Update
- [ ] Main Category Tab
- [ ] Main Category Create
- [ ] Main Category Update
- [ ] Subcategory Tab
- [ ] Subcategory Create
- [ ] Subcategory Update
- [ ] Item Tab
- [ ] Item Create
- [ ] Item Update
- [ ] Client Tab
- [ ] Client Create
- [ ] Client Update
- [ ] User Main Screen
- [ ] User Create + Initial Privileges
- [ ] User Update (Account Details)
- [ ] User Update (Privileges)
